name: 'TODO Comment Checker'
description: 'Search git diff for TODO comments and create PR comments'
author: 'Your Name'

inputs:
  github-token:
    description: 'GitHub token for API access'
    required: true
  todo-pattern:
    description: 'Pattern to search for TODO comments'
    required: false
    default: 'TODO:'
  comment-prefix:
    description: 'Prefix for PR comments'
    required: false
    default: '💡 **TODO Found**'

outputs:
  todos-found:
    description: 'Number of TODO comments found'
  comments-created:
    description: 'Number of PR comments created'

runs:
  using: "composite"
  steps:
    - name: Install Dependencies
      run: |
        ls
        pwd
        pip install -r requirements.txt
      shell: bash
    - name: Run TODO Checker
      id: todo_checker
      run: >
        python src/todo_checker.py 
        --github-token ${{ inputs.github-token }} 
        --todo-pattern "${{ inputs.todo-pattern }}"
        --comment-prefix "${{ inputs.comment-prefix }}"
      shell: bash
